name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- python=3.5
- numpy
- astropy
- scipy
- astroquery
- matplotlib
- pandas

- pip:
  - tornado<6.0
  - jupyter
  - git+https://github.com/eteq/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git