name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- numpy=1.15.4
- astropy
- scipy
- astroquery
- matplotlib
- pandas

- pip:
  - pip install tornado<6.0
  - pip install jupyter
  - git+https://github.com/eteq/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git