name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- numpy=1.15.2
- astropy
- scipy
- astroquery
- matplotlib
- pandas

- pip:
  - tornado==5.1.1
  - jupyter==1.0.0
  - git+https://github.com/eteq/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git