name: jwst_validation_notebooks

channels:
- astropy
- astropy-ci-extras
- http://ssb.stsci.edu/astroconda
- defaults

dependencies:
- python=3.6
- numpy=1.15.2
- matplotlib=3.0.1
- astropy
- scipy

- pip:
  - tornado==5.1.1
  - jupyter==1.0.0
  - git+https://github.com/eteq/nbpages.git
  - git+https://github.com/spacetelescope/jwst.git